### PR TITLE
API Implementation

### PR DESCRIPTION
**Pull request by kellikuramoto**

### CODE REVIEW

**Comment by mvkashyap** [comment]
LGTM

**Review by mvkashyap — APPROVED** [review]

**Comment by vrrock** [comment]
Get rid of the comments!

**Comment by GingLuo** [comment]
remove comments

**Comment by jhyrbc** [comment]
LGTM!

**Comment by GingLuo** [comment]
LGTM

**Comment by vrrock** [comment]
LGTM

**Review by jhyrbc — COMMENTED** [review]
LGTM

**Pull request merged**
