### PR TITLE
Updated swagger documentation

### PR DESCRIPTION
**Pull request by kellikuramoto**

### CODE REVIEW

**Review by mvkashyap — APPROVED** [review]

**Comment by vrrock** [comment]
LGTM!

**Review by jhyrbc — COMMENTED** [review]
Fixed some typos and LGTM!

**Review by jhyrbc — APPROVED** [review]

**Comment by vrrock** [comment]
LGTM

**Comment by GingLuo** [comment]
LGTM

**Review by GingLuo — APPROVED** [review]

**Pull request merged**
